version: '3'
services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "1337:1337"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app  # Changed from ./app to .
      - /usr/src/app/node_modules  # This is to avoid overwriting node_modules with the local folder

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
